// Default seed services placed inside the real Chandgaon boundary
// (OSM landuse=residential polygon, public/geojson/chandgaon.geojson).
// These seed MongoDB on first load and act as a client-side fallback when
// the database is unreachable. Coordinates are placeholders (real ones will
// be provided later) but every point sits inside the village polygon.
export const DEFAULT_SERVICES = [
  {
    name: "Primary Health Center",
    category: "hospital",
    latitude: 19.956059,
    longitude: 74.703747,
    phone: "9876543210",
    address: "Main Road, Chandgaon",
    description: "Government primary health centre with OPD and pharmacy.",
    workingHours: "9 AM - 5 PM",
    verified: true,
  },
  {
    name: "Chandgaon Medical Store",
    category: "medical_store",
    latitude: 19.955174,
    longitude: 74.704414,
    phone: "9876500011",
    address: "Near PHC, Chandgaon",
    description: "General medicines and first-aid supplies.",
    workingHours: "8 AM - 9 PM",
    verified: true,
  },
  {
    name: "Zilla Parishad Primary School",
    category: "school",
    latitude: 19.955366,
    longitude: 74.705589,
    phone: "9876500022",
    address: "School Road, Chandgaon",
    description: "Government primary school (Std 1-7).",
    workingHours: "7 AM - 1 PM",
    verified: true,
  },
  {
    name: "Anganwadi Center No. 1",
    category: "anganwadi",
    latitude: 19.95575,
    longitude: 74.702848,
    phone: "9876500033",
    address: "Ward 2, Chandgaon",
    description: "Child care and nutrition centre.",
    workingHours: "9 AM - 2 PM",
    verified: true,
  },
  {
    name: "Gram Panchayat Office",
    category: "panchayat",
    latitude: 19.955943,
    longitude: 74.703044,
    phone: "9876500044",
    address: "Village Center, Chandgaon",
    description: "Local self-government office for the Gram Panchayat.",
    workingHours: "10 AM - 5 PM",
    verified: true,
  },
  {
    name: "Shri Vitthal Temple",
    category: "temple",
    latitude: 19.956519,
    longitude: 74.703827,
    address: "Temple Road, Chandgaon",
    description: "Village temple and community gathering point.",
    workingHours: "5 AM - 9 PM",
    verified: true,
  },
  {
    name: "Bank of Maharashtra",
    category: "bank",
    latitude: 19.956712,
    longitude: 74.704414,
    phone: "9876500055",
    address: "Market Road, Chandgaon",
    description: "Branch with deposit, loan and passbook services.",
    workingHours: "10 AM - 4 PM",
    verified: true,
  },
  {
    name: "SBI ATM",
    category: "atm",
    latitude: 19.956904,
    longitude: 74.705198,
    address: "Bus Stand Road, Chandgaon",
    description: "24x7 cash withdrawal.",
    workingHours: "Open 24 hours",
    verified: true,
  },
  {
    name: "Police Chowki",
    category: "police",
    latitude: 19.957288,
    longitude: 74.704414,
    phone: "100",
    address: "Highway Side, Chandgaon",
    description: "Village police outpost.",
    workingHours: "Open 24 hours",
    verified: true,
  },
  {
    name: "Village Water Tank",
    category: "water",
    latitude: 19.956135,
    longitude: 74.70324,
    address: "Overhead Tank, Chandgaon",
    description: "Main drinking water storage and distribution point.",
    workingHours: "Supply: 6-8 AM, 5-7 PM",
    verified: true,
  },
  {
    name: "Chandgaon Bus Stop",
    category: "bus_stop",
    latitude: 19.957673,
    longitude: 74.704806,
    address: "State Highway, Chandgaon",
    description: "State transport bus stop connecting nearby towns.",
    workingHours: "5 AM - 10 PM",
    verified: true,
  },
  {
    name: "Public Washroom",
    category: "toilet",
    latitude: 19.956327,
    longitude: 74.70324,
    address: "Near Bus Stop, Chandgaon",
    description: "Public toilet block (ladies & gents).",
    workingHours: "Open 24 hours",
    verified: true,
  },
];
